#schema.yml

version: 2

sources:
  - name: raw
    schema: gw_raw_data
    tables:
      - name: adwords
        identifier: raw_gz_adwords
        description: data connected to the adwords  
        tests:
          - unique:
              column_name: "(date_date|| '-' || campaign_key)"         
        columns:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: source of the campaign
          - name: campaign_key
            description: unique key identifying the campaign
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the ads in euro
          - name: impression
            description: number of persons who viewed the campaign on this platform
          - name: click
            description: number of clicks generated through campaign
      - name: bing
        identifier: raw_gz_bing
        description: data connected to bing  
        tests:
          - unique:
              column_name: "(date_date|| '-' || campaign_key)"             
        columns:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: source of the campaign
          - name: campaign_key
            description: unique key identifying the campaign
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the ads in euro
          - name: impression
            description: number of persons who viewed the campaign on this platform
          - name: click
            description: number of clicks generated through campaign
      - name: criteo
        identifier: raw_gz_criteo
        description: data connected to criteo  
        tests:
          - unique:
              column_name: "(date_date|| '-' || campaign_key)"              
        columns:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: source of the campaign
          - name: campaign_key
            description: unique key identifying the campaign
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the ads in euro
          - name: impression
            description: number of persons who viewed the campaign on this platform
          - name: click
            description: number of clicks generated through campaign
      - name: facebook
        identifier: raw_gz_facebook
        description: data connected to facebook    
        tests:
          - unique:
              column_name: "(date_date|| '-' || campaign_key)"            
        columns:
          - name: date_date
            description: date of the campaign
          - name: paid_source
            description: source of the campaign
          - name: campaign_key
            description: unique key identifying the campaign
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the ads in euro
          - name: impression
            description: number of persons who viewed the campaign on this platform
          - name: click
            description: number of clicks generated through campaign
      - name: sales
        identifier: raw_gz_sales
        description: sales of Greenweez / we have one row per product_id found in each orders_id
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        # Freshness testing
        freshness:
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        columns:
          - name: date_date
            description: date of the sale
          - name: orders_id
            description: id number identifying the order
          - name: pdt_id
            description: id of pdt
          - name: revenue
            description: revenue generated from the order
          - name: quantity
            description: number of items sold in this order
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: id identifying the product
            tests:
              - unique 
              - not_null
          - name: purchase_price
            description: price of the item
      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: id identifying the order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: fee payed for shipping
          - name: logCost
            description: cost of log
          - name: ship_cost
            description: cost of shipping

